### ISSUE TITLE
Accessing local folder

### ISSUE THREAD

**Issue by aguileraGit** [bernhard-42/jupyter-cadquery#104]
I've converted the docker command to docker compose. I want to map the $WORKDIR to point to a directory on my host. Any thoughts on how to do this?

**Docker compose**
```
name: jupyter-cadquery
services:
    jupyter_cadquery:
      stdin_open: true
      tty: true
      volumes:
          - '/home/diegoaguilera/Projects:/home/diegoaguilera'
      ports:
          - 8889:8889
      image: bwalter42/jupyter_cadquery:3.5.2
      network_mode: host
      restart: unless-stopped
```
